### PR TITLE
Revised manufacturers and fixed rubocop syntax offenses

### LINKED ISSUE #183: Revised layout for /manufacturers

### PR DESCRIPTION
**Pull request by timlkelly**

### CODE REVIEW

**Comment by sethherr** [comment]
Removing the `Ready for review` label until we have the jquery datatables setup and functioning on the revised page.

File: app/assets/javascripts/revised/pages/info/manufacturers.js.coffee [hunk 1]
```diff
@@ -1,13 +1,11 @@
-class BikeIndex.Views.ContentManufacturers extends Backbone.View
-
-  initialize: ->
+class BikeIndex.InfoManufacturers extends BikeIndex
```
Comment (sethherr) [inline app/assets/javascripts/revised/pages/info/manufacturers.js.coffee]: We aren't using Backbone in the revised view - so the classes are instantiated differently. If you look at one of the other files in this folder (e.g. [where.coffee](https://github.com/bikeindex/bike_index/blob/master/app/assets/javascripts/revised/pages/info/where.coffee), you can see the way we name classes.

File: app/assets/javascripts/revised/pages/info/manufacturers.js.coffee [hunk 2]
```diff
@@ -1,13 +1,11 @@
...
+  constructor: ->
```
Comment (sethherr) [inline app/assets/javascripts/revised/pages/info/manufacturers.js.coffee]: Similarly, because no backbone - `constructor` is the method that is called on initialization, unlike `initialize`, which is a fancy backbone thing.

File: app/assets/javascripts/revised/pages/info/manufacturers.js.coffee [hunk 3]
```diff
@@ -1,13 +1,11 @@
...
+    console.log 'parttttt'
```
Comment (sethherr) [inline app/assets/javascripts/revised/pages/info/manufacturers.js.coffee]: You should delete this. Ooops.

File: app/assets/stylesheets/revised.scss [hunk 4]
```diff
@@ -3,6 +3,7 @@
  * things from rails-assets
  *= require pikaday
  *= require selectize/selectize.bootstrap3.scss
+ *= require dataTables/bootstrap/3/jquery.dataTables.bootstrap
```
Comment (sethherr) [inline app/assets/stylesheets/revised.scss]: Because we're using a .scss file instead of a .css file, the fancy import sprockets stuff is at the top, and then we import stuff using `@import` - this is because `@import` allows you to define variables/mixins in one file and use them in another, so we use it wherever we can.

File: app/assets/stylesheets/revised/sections/datatables.scss [hunk 5]
```diff
@@ -0,0 +1,11 @@
+// Datatables pagination
+// it uses outdated shit. Has to be overridden. It has to be overridden hard.
```
Comment (sethherr) [inline app/assets/stylesheets/revised/sections/datatables.scss]: Fuck you datatables

**Comment by sethherr** [comment]
@timlkelly I made some comments.

**Comment by timlkelly** [comment]
Datatables seems to be working with the rest of the site now, and I can't reproduce the sprockets error. Can you double check this please.
